### ISSUE TITLE
8 bit mode SSD1289

### ISSUE THREAD

**Issue by ematt** [WiseLord/ampcontrol-f103#1]
Hello,

I have always dreamed to have my own audio system, I got a real interest in this project. 

I am trying to get this software working with a TFT_320QVT([pictures](https://www.amazon.ca/XCSOURCE-240x320-Screen-Driver-SSD1289/dp/B00XXEJLZU)) display in 8 bit mode without any success. Unfortunately I got little to no experience with graphical LCD's. I am stuck with a blank screen.

The progress so far:

**About the display**:
The seller states that the lcd controller is SSD1289
I have moved the R4 resistor to R5 to enable 8 bit interface as  matherp states here https://www.thebackshed.com/forum/forum_posts.asp?TID=7903 and soldered the J1 jumper because VCC is already 3.3V

**About the STM32 board**
Is a Blue Pill(STM32F103C8T6) dev board: https://wiki.stm32duino.com/index.php?title=Blue_Pill
I am using an ST-LINK v2 emulator to program it
gdb shows that the software runs normally on the STM32

**Wiring**:

Blue pill | LCD
-------- | --------
A0..A7 | DB0..DB7
B12 | CS
B14 | RS
B15 | WR
G | GND
3.3 | VCC

LED's LED_A is connected to a 3.3V in from the ST-LINK

**Project setup**:
```
diff --git a/Makefile b/Makefile
index 2abc0e2..c4098ab 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 PROJECT = ampcontrol_f103
 
-DISPLAY = ILI9341
-DISPVAR = SPI
+DISPLAY = SSD1289
+DISPVAR = 8BIT
 
 APROC_LIST = TDA7439 TDA731X PT232X TDA7418
 TUNER_LIST = RDA580X SI470X TEA5767
@@ -195,7 +195,7 @@ CFLAGS += -MMD -MP -MT $(BUILD_DIR)/$(*F).o -MF $(BUILD_DIR)/$(*D)/$(*F).d
 LDSCRIPT = system/stm32f103c8tx_flash.ld
 LIBS = -lc -lm -lnosys
 LIBDIR =
-LDFLAGS = $(MCU) -specs=nosys.specs -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections
+LDFLAGS = $(MCU) -specs=nosys.specs -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections -L/usr/lib/arm-none-eabi/newlib/thumb
 #LDFLAGS = $(WARN) -mmcu=$(MCU) -Wl,--gc-sections -Wl,--relax
 
 # Main definitions
diff --git a/ampcontrol-f103.config b/ampcontrol-f103.config
index 77b055d..5716896 100644
--- a/ampcontrol-f103.config
+++ b/ampcontrol-f103.config
@@ -10,12 +10,13 @@
 //#define _LPH9157
 //#define _LS020
 //#define _SSD1286A
+#define _SSD1289
 
 //#define _HX8340
 //#define _ILI9225
 
 //#define _ILI9320
-#define _ILI9341
+//#define _ILI9341
 //#define _MC2PA8201
 //#define _S6D0129
 //#define _S6D0139
@@ -28,9 +29,9 @@
 //#define _ILI9486
 //#define _R61581
 
-//#define _DISP_8BIT
+#define _DISP_8BIT
 //#define _DISP_16BIT
-#define _DISP_SPI
+//#define _DISP_SPI
 //#define _DISP_HI_BYTE
 #define _DISP_LO_BYTE
 #define _DISP_320x240
diff --git a/pins.h b/pins.h
index 5cd9fe1..02ddf32 100644
--- a/pins.h
+++ b/pins.h
@@ -69,9 +69,9 @@ void pinsSetStby(bool value);
 #define RC_AR_ExtiLine          LL_GPIO_AF_EXTI_LINE8
 
 // TFT LCD pins
-#define DISP_DATA_LO_Port       GPIOB
-#define DISP_DATA_LO_Pin        (LL_GPIO_PIN_0 | LL_GPIO_PIN_1 | LL_GPIO_PIN_2 | LL_GPIO_PIN_3 | \
-                                 LL_GPIO_PIN_4 | LL_GPIO_PIN_5 | LL_GPIO_PIN_6 | LL_GPIO_PIN_7)
+#define DISP_DATA_LO_Port       GPIOA
+#define DISP_DATA_LO_Pin        (LL_GPIO_PIN_0 | LL_GPIO_PIN_1 | LL_GPIO_PIN_3 | LL_GPIO_PIN_4 | \
+                                 LL_GPIO_PIN_5 | LL_GPIO_PIN_6 | LL_GPIO_PIN_7 | LL_GPIO_PIN_2)
 
 // TFT parallel (8-bit) wiring
 #define DISP_CS_Port            GPIOB

```

**Comment by WiseLord** [comment]
Did you try other drivers? I have an 8bit display with absolutely the same
pinout, but with ILI9431 controller. Also, originally it was 16bit and I
had to resolder a resistor on its flex board to switch it to 8bit.

сб, 18 мая 2019 г., 12:01 ematt <notifications@github.com>:

**Comment by WiseLord** [comment]
also, do you have RD pulled up?

сб, 18 мая 2019 г., 12:33 WiseLord <wiselord1983@gmail.com>:

**Comment by ematt** [comment]
Thank you for the quick response!

RD is now pulled up and I've added a 100uF capacitor between VCC and GND on the LCD board.
Tried all other drivers with the same result, the screen remains blank.

Could you tell if wiring is right?

**Comment by WiseLord** [comment]
Wiring looks OK. I guess the problem is that display might not properly
switched to 8bit mode.
I had a similar problem with similar LCD and first just put my display
aside. But later the guy who added the support of most display controllers
in this project gave me some hints about switching to 8bit.

сб, 18 мая 2019 г., 14:00 ematt <notifications@github.com>:

**Comment by ematt** [comment]
I got it working with the following wiring:

Blue pill | LCD
-- | --
A0..A7 | DB0..DB7
B12 | CS
B14 | RS
B15 | WR
G | GND
3.3 | VCC

LCD pin | -
-- | --
RD | VCC
RESET | VCC
LED_A | VCC

Thank you so much for your help!
